// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: '快速上手',
      items: [
        'getting-started/use-systemd',
        {
          type: 'category',
          label: '使用源码运行',
          items: [
            {
              type: 'autogenerated',
              dirName: 'getting-started/use-source-code',
            }
          ]
        },
      ],
    },
    {
      type: 'category',
      label: '进阶',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced',
        },
      ],
    },
    'use-docker',
  ],

  api: [
    {
      type: "autogenerated",
      dirName: "api",
    }
  ]
};

export default sidebars;
